load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "csh",
    srcs = ["simple_shell.c", "parser.c", "string_functions.c", "helper_funcs.c", "_putchar.c", "helper_funcs2.c",  "holberton.h"],
)
